### ISSUE TITLE
Grafana use case and authorization error

### ISSUE THREAD

**Issue by dmlabs** [appuio/openshift-prometheus-proxy#2]
Dear Appuio Team

We have found your project and it looks promising for one of our customer use cases together with Grafana. We are having a hard time getting the application working and we want to ask you a few questions before we do any further troubleshooting.

1. Is the project actively used at Appuio and can your recommend it for production?
2. Is it possible to use the openshift-prometheus-proxy as a proxy between Grafana and Prometheus?  
    Example:  
     - User A ---> Grafana ---> openshift-prometheus-proxy ---> OpenShift Prometheus => return user A namespaces metrics
     - User B ---> Grafana ---> openshift-prometheus-proxy ---> OpenShift Prometheus => return user B namespaces metrics
3. Unfortunately, when starting the pod on OpenShift v4.6, we get the following error message:
    ```
    Traceback (most recent call last):
      File "app.py", line 166, in <module>
        httpd = ProxyHTTPServer(('127.0.0.1', 8080), partial(ProxyMetricsHandler, ProxyConfig()))
      File "app.py", line 48, in __init__
        self.service_account_token = self.k8s_config.api_key['authorization'].partition(' ')[2]
    KeyError: 'authorization'
    ```
    Does this error sound familiar to you and do you know how to fix it?

Thanks in advance for your help.

Kind regards,
Domenic

**Comment by arska** [comment]
The missing authorization api_key is fixed by #3, I don't know about questions 1 and 2 :)
